### PR TITLE
Add JavaScript Standard Style linting

### PR DESCRIPTION
**Pull request by geymed**
- [x] Add JS Standard
 - [x] Add script to run linting
 - [x] Fix linting errors
 - [x]  Run lint and tests in Travis CI

Solves issue #2

### CODE REVIEW

**Comment by joeljuca** [comment]
I'll take care of these vulnerabilities being caught by Node Security.

**Comment by joeljuca** [comment]
@geymed could you please rebase this branch to make it up to date with `master`?

**Comment by geymed** [comment]
@joelwallis done rebasing with up to date master

**Comment by joeljuca** [comment]
Great work @geymed!

**Comment by geymed** [comment]
Thanks @joelwallis, glad to help!

**Pull request merged**
